# Generated by Django 2.2.5 on 2020-04-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
