# Generated by Django 2.2.5 on 2020-04-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0004_blog_faq_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Phone number')),
                ('service', models.CharField(blank=True, max_length=40, verbose_name='Service')),
                ('time', models.TimeField(blank=True, verbose_name='Time')),
                ('date', models.DateField(blank=True, verbose_name='Date')),
            ],
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
