# Generated by Django 2.2.1 on 2020-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0006_auto_20200428_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttestimonial',
            name='client_picture',
            field=models.ImageField(blank=True, upload_to='clients/', verbose_name='Client picture'),
        ),
    ]
