# Generated by Django 2.2.1 on 2020-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0007_auto_20200429_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_picture',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Blog picture'),
        ),
    ]
