# Generated by Django 2.2.1 on 2020-04-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0008_auto_20200429_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
    ]
