# Generated by Django 2.2.1 on 2020-04-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0009_remove_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Time'),
        ),
    ]
